blog/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path(r'', views.main, name="main"), 
    path('posts/', views.PostListMain.as_view(), name="posts"),
    path('add_post/', views.AddPostView.as_view(), name="add_post"),    
    path('searchpost/', views.PostListMain.as_view(), name="search"),
    path('<slug:category_slug>/', views.CategoryListMain.as_view(), name='category_list_main'), 
    path('post/<slug:slug>/', views.ShowPost.as_view(), name="post_url")
]

learnsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('tinymce/', include('tinymce.urls')),
    path('', include('blog.urls')),
    path('', include('profiles.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from PIL import Image 
from django.urls import reverse
from django.contrib.auth.models import User
from profiles.models import UserProfile

class Category(models.Model):
    name = models.CharField(max_length=80)
    info = models.TextField(blank=True)
    category_slug = models.CharField(max_length=80, default="category_main")
    img = models.ImageField(upload_to='images/',
                            height_field=None,
                            width_field=None,
                            verbose_name="Зображення категорії", 
                            default='default.jpg')
    class Meta:
        verbose_name_plural = "Категорії"
    def save(self,*agr, **kwargs):
        super().save()
        img = Image.open(self.img.path)
        if img.height>200 or img.width>200:
            img.thumbnail((200, 200))
            img.save(self.img.path)
    def __str__(self):
        return f"{self.name}"
        # return f"{self.name}   URL: {self.category_slug}"

from django.urls import reverse

class Post(models.Model): 
    writer = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=100) 
    text = models.TextField()
    created_at = models.DateField(default=timezone.now) 
    post_slug = models.CharField(max_length=80, default="default_post") 
    img = models.ImageField(default='images/default.jpg', upload_to='images/', 
                            height_field=None, width_field=None,
                            max_length=200,
                            verbose_name="Картинка для поста")
    category = models.ForeignKey(Category, default=1, 
                                 on_delete=models.SET_DEFAULT,
                                 verbose_name="Категорія")

    def __str__(self): 
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.img.path)
        if img.height > 650 or img.width > 650:
            img.thumbnail((650, 650))
            img.save(self.img.path)

    def get_absolute_url(self):
        return reverse('post_url', args=[self.post_slug])

blog/forms.py
# from django import forms
# from django.contrib.auth.models import User
# from django.contrib.auth.forms import UserCreationForm

from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Post, Category
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.contrib.admin.sites import site


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder':'Введіть ім\'я...'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control', 'placeholder':'Введіть пароль...'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control', 'placeholder':'Підтвердіть пароль...'})

from django import forms
from .models import Post, Category, UserProfile

class PostForm(forms.ModelForm):
    category = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', 'list': 'category-list', 'placeholder': 'Виберіть або введіть категорію'})
    )

    class Meta:
        model = Post
        fields = ('title', 'text', 'img', 'post_slug', 'category')
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'post_slug': forms.TextInput(attrs={'class': 'form-control'}),
        }

    def clean_category(self):
        category_name = self.cleaned_data.get('category').strip()
        if not category_name:
            raise forms.ValidationError("Оберіть або введіть категорію.")

        category, created = Category.objects.get_or_create(name=category_name)
        return category

    def clean_post_slug(self):
        post_slug = self.cleaned_data.get('post_slug')
        post_id = getattr(self.instance, 'id', None)
        existing_post = Post.objects.filter(post_slug=post_slug).exclude(id=post_id)
        print(f"Existing post count: {existing_post.count()}")  # Debugging
        if existing_post.exists():
            raise forms.ValidationError('Цей slug вже зайнятий. Виберіть інший.')
        return post_slug


    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.category = self.cleaned_data['category']
        if commit:
            instance.save()
        return instance

blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Category
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic import DetailView, CreateView
from .forms import CustomUserCreationForm
from .forms import PostForm
from django.core.exceptions import ValidationError

def loginUser(request):
    page = 'login'
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('main')

    return render(request, 'login_register.html', {'page':page})

def logoutUser(request):
    logout(request)
    return redirect('login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])  # встановлення пароля
            user.save()  # збереження користувача в базу даних

            # Тепер ми можемо аутентифікувати користувача з новим паролем
            user = authenticate(request, username=user.username, password=request.POST['password1'])
            
            if user is not None:
                login(request, user)  # авторизація користувача
                return redirect('main')  # перенаправлення на головну сторінку

    context = {'form': form, 'page': page}
    return render(request, 'login_register.html', context)



@login_required(login_url='login') 
def main(request, *args):
    page = request.GET.get('page')
    category = Category.objects.all()
    data_dict = {
        'category': category,
    }
    return render(request, 'main.html', data_dict)



class PostListMain(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'posts.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slide_posts'] = Post.objects.all().order_by('title')  # Додаємо сортування для slide_posts
        context['category'] = Category.objects.all()
        return context

    def get_queryset(self):
        search_query = self.request.GET.get("searchpost")
        queryset = Post.objects.all()

        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query.lower()) |
                Q(title__icontains=search_query.upper()) |
                Q(title__icontains=search_query.capitalize())
            )

        return queryset.order_by('title')  # Завжди сортуємо за 'id'

class CategoryListMain(LoginRequiredMixin, ListView):
    model = Post
    template_name = "category.html"
    context_object_name = 'posts'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()  # для меню
        
        # Отримання вибраної категорії за допомогою slug
        slug = self.kwargs['category_slug']
        try:
            selected_category = Category.objects.get(category_slug=slug)
        except Category.DoesNotExist:
            selected_category = None
        context['selected_category'] = selected_category
        return context

    def get_queryset(self):
        slug = self.kwargs['category_slug']
        return Post.objects.filter(category__category_slug=slug)

class ShowPost(LoginRequiredMixin, DetailView):
    model = Post
    template_name = "post_view.html"
    slug_url_kwarg = "slug"
    context_object_name = 'post'
    def get_object(self):
        slug = self.kwargs['slug']
        obj_post = Post.objects.get(post_slug = slug)
        return obj_post
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context
    
class AddPostView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "add_post.html"

    def form_valid(self, form):
        post_slug = form.cleaned_data['post_slug']
        
        if Post.objects.filter(post_slug=post_slug).exists():
            form.add_error('post_slug', 'This slug is already taken. Please choose another one.')
            return self.form_invalid(form)  
        post = form.save(commit=False) 
        post.writer = self.request.user.userprofile  
        post.save()  
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()  
        return context
    

# Функція для створення посту
def create_post(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('post_list')
    else:
        form = PostForm()
    return render(request, 'post_form.html', {'form': form, 'categories': categories})

blog/templates/add_post.html
{% extends 'navbar.html' %}

{% block content %}

<div class="add-post-container mt-5">
    <div class="add-post-form-container">
        <h1 class="add-post-title">Додати пост...</h1>
        <form method="POST" enctype="multipart/form-data" id="addPostForm">
            {% csrf_token %}

            <div class="add-post-form-group">
                <label for="{{ form.title.id_for_label }}">Назва посту</label>
                {{ form.title }}
            </div>

            <input list="categories" name="category" id="id_category" class="form-control" placeholder="Введіть або виберіть категорію">
            <datalist id="categories">
                {% for cat in category %}
                    <option value="{{ cat.name }}">
                {% endfor %}
            </datalist>

            <div class="add-post-form-group">
                <label for="{{ form.text.id_for_label }}">Текст</label>
                {{ form.text }}
            </div>

            <div class="add-post-form-group image">
                <label for="{{ form.img.id_for_label }}">Зображення</label>
                {{ form.img }}
            </div>

            <div class="add-post-form-group">
                <label for="{{ form.post_slug.id_for_label }}">Посилання на пост</label>
                {{ form.post_slug }}
                <div class="slug-tooltip">Посилання на пост має бути унікальним та не рівним "default_post".</div>
                {% if request.method == "POST" %}
                {% if form.post_slug.errors %}
                    <div class="invalid-feedback" style="display: block;">
                        {% for error in form.post_slug.errors %}
                            <p>Це посилання вже зайняте. Оберіть інше.</p>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if form.post_slug.value == "default_post" %}
                    <div class="invalid-feedback" style="display: block;">
                        <p>Посилання на пост не може бути "default_post".</p>
                    </div>
                {% endif %}
            {% endif %}
            
            </div>
            <button type="submit" class="btn btn-add-post">Створити пост</button>
        </form>
    </div>
</div>

{% endblock %}

blog/templates/blog_main.html
{% extends 'navbar.html' %}

            {% block carousel %}
            <div class = "container hide-on-med-and-down">
                <div class="carousel carousel-slider center">
                    {% for post in slide_posts %}
                    <div class="carousel-item white white-text" href="/{{ post.post_slug }}">
                        <div class="card">
                            <span class="card-title">
                                <b><h4><a href="/{{ post.post_slug }}">{{ post.title }}</a></h4></b>
                            </span>
                            <div class="card-image">
                                <img class = "center-align responsive-img"
                                src="/{{ post.img }}">
                            </div>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    var elems = document.querySelectorAll('.carousel');
                    var instances = M.Carousel.init(elems, {
                        fullWidth: false,
                        indicators: true,
                        numVisible: 3,
                        dist: -200,
                    });
                });
            </script>
            {% endblock  %}

    {% block content %}
    <div class = "container">
        <br><br><br>
        {% if posts %}
            <div class = "row">
                {% for post in posts %}
                {% if forloop.first %}
                <div class="col s2 l2">
                </div>
                <div class = "col s10 l5">
            {% else %}
                    {% if forloop.counter|divisibleby:2 %}
                        <div class="col s2">
                        </div>
                        <div class="col s10 l5">    
                    {%else%}
                        <div class="col s10 l5 offset-s2 offset-l2">
                    {% endif %}
            {% endif %}
                        <div class="card hoverable">
                            <div class="card-image">    
                                <img class = "center-align responsive-img">
                                    <img src="/{{ post.img }}">
                                <a class="btn btn-floating btn-large halfway-fab pulse activator #ef5350 red lighten-1"><i class="material-icons right">add</i></a>
                            </div>

                            <div class="card-content">
                                <span class="card-title">
                                    <b><h4><a href="/{{ post.post_slug }}">{{ post.title }}</a></h4></b>
                                </span>
                            </div>

                            <div class="card-reveal">
                                <span class="card-title"><a href="/{{ post.post_slug }}">{{ post.title }}</a><i class="material-icons right">close</i></span>
                                <p><div class="card-content">{{ post.text|truncatechars:150 }}...</div></p>
                            </div>
                            <br>
                        </div>
                    </div>
                {% endfor %}
            </div>
        
            <div class="row center-align">
                <div class = "col s2">
                </div>
                <ul class="pagination">
                    {% if posts.has_previous %}
                        <li class="waves-effect"><a href="?page={{ posts.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                    {% else %}
                        <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
                    {% endif %}

                    {% for num in posts.paginator.page_range %}
                        {% if posts.number == num %}
                            <li class="active"><a href="">{{num}}</a></li>
                        {% else %}
                            <li class="waves-effect"><a href="?page={{ num }}">{{num}}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if posts.has_next %}
                        <li class="waves-effect"><a href="?page={{ posts.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                    {% else %}
                        <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
                    {% endif %}
                </ul>                
            </div>

        {% endif %}
    </div>
    {% endblock %}

blog/templates/category.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="container">
        <br>
        {% if posts %}
        <div class="row center-align">
            {% for post in posts %}
                {% if forloop.counter0|divisibleby:2 %}
                    <div class="col s12 m10 offset-m1 l8 offset-l2">
                        <div class="row">
                {% endif %}
                            <div class="col s12 m6">
                                <div class="card_post card hoverable">
                                    <div class="card-image">    
                                        <img class="center-align responsive-img" src="{{ post.img.url }}">
                                        <a class="btn btn-floating btn-large halfway-fab pulse-button activator">
                                            <i class="material-icons right" id="add_btn">add</i>
                                        </a>
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title">
                                            <b><h5><a href="/post/{{ post.post_slug }}" class="card_post_title">{{ post.title }}</a></h5></b>
                                        </span>
                                    </div>
                                    <div class="card-reveal card_rev">
                                        <span class="card-title" id="card_post_title">
                                            <a href="/post/{{ post.post_slug }}" id="post_rev_title">{{ post.title }}</a>
                                            <i class="material-icons right" id="close_btn">close</i>
                                        </span>
                                        <p>
                                            <div class="card-content">{{ post.text|truncatechars_html:70|safe }}</div>
                                        </p>
                                    </div>
                                    <br>
                                </div>
                            </div>
                    {% if forloop.counter|divisibleby:2 or forloop.last %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
        
        {% endif %}

        <div class="row center-align">
            <div class="col s12">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                    {% else %}
                        <li class="disabled"><a href=""><i class="material-icons">chevron_left</i></a></li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="active #e65100 green"><a href="">{{ num }}</a></li>
                        {% else %}
                            <li class="waves-effect"><a href="?page={{ num }}">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                    {% else %}
                        <li class="disabled"><a href=""><i class="material-icons">chevron_right</i></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    <br><br>

    <footer>
        <div class="post_footer">
            <div class="row">
                <h5><b>Ви долистали до кінця!</b></h5>                           
                <p>Джерело інформації: www.education.ua</p>                                        
                <p>Дані розробника:</p>
                <p><i>Instagram</i> - korovay_z_sillyu</p>
                <p><i>Email</i> - vladahvala8@gmail.com</p>
            </div>
        </div>
        <div class="footer-copyright_post">
            <p>© Programming.ua</p>
        </div>
    </footer>

{% endblock %}

blog/templates/login_register.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Login/Register</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login_style.css' %}?v={{ timestamp }}">

    <style>
        body {
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            background-image: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)),
                                url("{% static 'img/login_wallpaper/log_in_wallpaper.jpg' %}") ;
            background-size: cover;
            background-position: center;
        }
    </style>
    
</head>

<body>
    <div class="glass-container">
        <div class="login-box">
            {% if page == 'login' %}
        <form method='post' class="form">
            {% csrf_token %}
            <h2>Login</h2>
            <input type="text" class="form-control" placeholder="Введіть логін..." name="username" id="username">
            <input type="password" class="form-control" placeholder="Введіть пароль..." name="password" id="password">
            
            <div class="options">
                <input type="checkbox" id="remember" name="remember">
                <label for="remember">Запам'ятати мене</label>
                <a href="#">Забули пароль?</a>
            </div>
            
            <button type="submit">Увійти</button>
            <p>Немає акаунту? <a href="{% url 'register' %}" id="register_text">Зареєструватися</a></p>
        </form>
    {% else %}
        <form method='post' class="form">
            {% csrf_token %}
            <h2>Реєстрація</h2>
            
            {% for field in form %}
                <!-- <label class="form-control">{{ field.label }}</label> -->
                {{ field }}
            {% endfor %}

            <button type="submit">Зареєструватися</button>
            <p>Уже є акаунт? <a href="{% url 'login' %}" id="register_text">Увійти</a></p>
        </form>
    {% endif %}

        </div>
    </div>
</body>
</html>

blog/templates/main.html
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Parallax</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'js/parallax.js' %}"></script>
</head>

<body>
    <ul class="sidenav" id="slide-out" style="background-color:#dce775">
        <div class="row center-align">
          <h3 class="sidenav_menu">меню</h3>
        </div>
        <li><a class="active" href="/"><i class="material-icons" id="sidenav_home">home</i>Головна</a></li>
        <li><a href="/posts"><i class="material-icons" id="sidenav_main">laptop_mac</i>Всі спеціальності</a></li>
        <li><a href="{% url 'login' %}"><i class="material-icons" id="sidenav_login">login</i>Ввійти</a></li>
        <li><a href="{% url 'logout' %}"><i class="material-icons" id="sidenav_logout">logout</i>Вийти</a></li>
        <li><a href="{% url 'account' %}"><i class="material-icons" id="sidenav_add">person</i>Акаунт</a></li>
    </ul>

      <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper #dce775 lime lighten-2">
                <div class="row">
                  <a href="/" data-target="slide-out" class="sidenav-trigger show-on-med-and-down"><i class="material-icons">menu</i></a>
                    <ul class="hide-on-med-and-down left">
                      <li><a class="waves-effect waves-light black-text" href="/">Головна</a></li>
                      <li><a class="waves-effect waves-light black-text" href="/posts">Всі спеціальності</a></li>
                      <!--<li><a class="waves-effect waves-light black-text" href="/admin">Адміністратор</a></li>-->
                  </ul>                
                </div>
              </div>
              <br>
            </div>
        </nav>

    <div class="parallax-container">
        <div class="parallax">
            <img src="{% static 'img/parallax/comp.jpg' %}" alt="works" class="responsive-img">            
        </div>
    </div>

    <div class="section_content">
            <div class="intro_par">
                <h1><b>Комп'ютерні спеціальності</b></h1>
                <p><i>Останнім часом професії у сфері IT набирають свою популярність...</i></p>
                <p>- по-перше, це дуже цікава діяльність, яка дозволяє створювати чудові продукти і проєкти власними руками;</p>
                <p>- по-друге, програмування і комп’ютерні спеціальності високо цінуються в сучасному суспільстві, тому справжні професіонали 
                    своєї справи можуть розраховувати на пристойну заробітну плату;</p>
                <p>- по-третє, робота з комп’ютерами не зобов’язує наявність офісу або певного місця праці, тому цілком своєю справою можна займатися вдома або в кафе.</p>
                <p>Крім цього, потрібно враховувати, що розвиток технологій зобов’язує всіх людей, так чи інакше, розбиратися в «залізі». Складно уявити, наскільки полегшило роботу деяких спеціальностях впровадження програм і комп’ютерів.</p>
                <p>Перспективи IT-професій зараз дуже цікавлять молодь. Тому в статті будуть розглянуті найпопулярніші, вигідні і прибуткові професії, пов’язані з комп’ютером.</p>
                <br><br>
            </div>       
    </div>       
    
    <div class="parallax-container">
        <div class="parallax">
            <img src="{% static 'img/parallax/code.jpg' %}" alt="works" class="responsive-img">   
        </div>
    </div>

    <div class="section_content">
        <div class="container">
            <h1 class="content_title">Зміст статті</h1>
            <div class="columns">
                <ul class="column">
                    <li>Адміністратор баз даних</li>
                    <li>Веб-дизайнер</li>
                    <li>Веб-програміст</li>
                    <li>Бізнес-аналітик</li>
                    <li>Верстальник</li>
                    <li>Консультант ERP-систем</li>
                    <li>Менеджер з продажу</li>
                    <li>Контент-менеджер</li>
                    <li>Менеджер інтернет-проєктів</li>
                    <li>Програміст</li>
                </ul>
                <ul class="column">
                    <li>Програміст 1С</li>
                    <li>Аналітик</li>
                    <li>Редактор сайтів</li>
                    <li>Системний адміністратор</li>
                    <li>Системний аналітик</li>
                    <li>Спеціаліст з безпеки інформації</li>
                    <li>Сценарист комп’ютерних ігор</li>
                    <li>Тестувальник ПЗ</li>
                    <li>ERP-програміст</li>
                    <li>HTML-верстальник</li>
                </ul>
            </div>
        </div>
    </div>
    

    <footer>
        <div class="main_footer">
            <div class="row">
                <h5><b>Ви долистали до кінця!</b></h5>                           
                <p>Джерело інформації: www.education.ua</p>                                        
                <p>Дані розробника:</p>
                <p><i>Instagram</i> - korovay_z_sillyu</p>
                <p><i>Email</i> - vladahvala8@gmail.com</p>
            </div>
        </div>
        <div class="footer-copyright_main">
            <p>© Programming.ua</p>
        </div>
    </footer>
      
</body>
</html>